#!/bin/sh
#deploy="false"
deploy="true"

image=Practical_Server
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t krishkapadia00/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push krishkapadia00/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag krishkapadia00/${image}:1.0-SNAPSHOT krishkapadia00/${image}:latest
        docker push krishkapadia00/${image}:latest
    fi
fi