#!/bin/sh
mvn clean package && docker build -t krishkapadia00/Exam_Server .
docker rm -f Exam_Server 2>/dev/null || true && docker run -it --name Exam_Server -p 8080:8080 -p 4848:4848 -p 8181:8181 --name Exam_Server krishkapadia00/Exam_Server
