#!/bin/sh
mvn clean package && docker build -t krishkapadia00/Practice_JWT_Server .
docker rm -f Practice_JWT_Server 2>/dev/null || true && docker run -it --name Practice_JWT_Server -p 8080:8080 -p 4848:4848 -p 8181:8181 --name Practice_JWT_Server krishkapadia00/Practice_JWT_Server
