#!/bin/sh
mvn clean package && docker build -t krishkapadia00/Practical_Client .
docker rm -f Practical_Client 2>/dev/null || true && docker run -it --name Practical_Client -p 8080:8080 -p 4848:4848 -p 8181:8181 --name Practical_Client krishkapadia00/Practical_Client
