#!/bin/sh
mvn clean package && docker build -t krishkapadia00/Practice-JWT_Client .
docker rm -f Practice-JWT_Client 2>/dev/null || true && docker run -it --name Practice-JWT_Client -p 8080:8080 -p 4848:4848 -p 8181:8181 --name Practice-JWT_Client krishkapadia00/Practice-JWT_Client
